name: alfred2
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9.0,<3.13
  - beautifulsoup4=4.12.3
  - pymupdf=1.25.1
  - pypdf=3.10.1
  - python-dotenv=1.0.1
  - numpy=1.26.0
  - pandas=2.0.3
  - scikit-learn=1.3.0
  - pyarrow=15.0.0
  - aiohttp=3.8.1
  - xmltodict=0.13.0
  - jsonpatch=1.33
  - dydantic=0.0.6
  - pytest-asyncio=0.23.7
  - tiktoken=0.7.0
  - black=24.4.2
  - isort=5.13.2
  - pytest=8.2.2
  - ruff=0.4.10
  - mypy=1.10.0

# Add pip dependencies for packages not available in Conda
  - pip
  - pip:
      - langgraph>=0.2.56,<0.3.0
      - langchain-pinecone==0.1.1
      - pinecone-client==3.2.2
      - langchain==0.2.8
      - langchain-openai==0.1.10
      - pydantic-settings==2.3.4
      - langgraph-sdk==0.1.23
      - langchain-community==0.2.6
      - tavily-python==0.3.3
      - langchainhub==0.1.15
      - langchain-chroma==0.1.0
      - langchain-core==0.2.4
      - langgraph-cli==0.1.43
